# Generated by Django 5.2.11 on 2026-09-27 18:45

import django.db.models.deletion
import uuid
from django.db import migrations, models

# DDL espejo de SIA-QR.md. Las tablas pueden venir creadas a mano,
# asi que todo es idempotente (IF NOT EXISTS / DO blocks).
CREATE_SESSIONS = """
CREATE TABLE IF NOT EXISTS attendance_sessions (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    class_id uuid NOT NULL REFERENCES scheduled_classes(id) ON DELETE CASCADE,
    token_hash varchar(64) NOT NULL UNIQUE,
    expires_at timestamptz NOT NULL,
    is_active boolean NOT NULL DEFAULT TRUE,
    created_at timestamptz DEFAULT CURRENT_TIMESTAMP
)
"""

CREATE_ATTENDANCES = """
CREATE TABLE IF NOT EXISTS attendances (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    session_id uuid NOT NULL REFERENCES attendance_sessions(id) ON DELETE CASCADE,
    student_id uuid NOT NULL REFERENCES students(id) ON DELETE CASCADE,
    registered_at timestamptz DEFAULT CURRENT_TIMESTAMP,
    latitude numeric(10, 8) NULL,
    longitude numeric(11, 8) NULL,
    accuracy numeric(8, 2) NULL,
    ip_address varchar(45) NOT NULL,
    user_agent text NOT NULL
)
"""

CREATE_INDEXES_AND_CONSTRAINTS = """
CREATE INDEX IF NOT EXISTS idx_attendance_sessions_token
    ON attendance_sessions(token_hash) WHERE is_active = TRUE;
CREATE INDEX IF NOT EXISTS idx_attendances_session ON attendances(session_id);
CREATE INDEX IF NOT EXISTS idx_attendances_student ON attendances(student_id);
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'unique_attendance_per_session') THEN
        ALTER TABLE attendances
            ADD CONSTRAINT unique_attendance_per_session UNIQUE(session_id, student_id);
    END IF;
END
$$;
"""


def create_attendance_tables(apps, schema_editor):
    cursor = schema_editor.connection.cursor()
    cursor.execute(CREATE_SESSIONS)
    cursor.execute(CREATE_ATTENDANCES)
    cursor.execute(CREATE_INDEXES_AND_CONSTRAINTS)
    SystemConfig = apps.get_model("attendance", "SystemConfig")
    SystemConfig.objects.get_or_create(
        config_key="QR_DEFAULT_MINUTES", defaults={"config_value": "10"}
    )
    SystemConfig.objects.get_or_create(
        config_key="FRONTEND_URL", defaults={"config_value": "http://localhost:3000"}
    )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_scheduledclass_qr_duration_minutes'),
        ('attendance', '0001_initial'),
        ('authentication', '0004_student'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='AttendanceSession',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('token_hash', models.CharField(max_length=64, unique=True)),
                        ('expires_at', models.DateTimeField()),
                        ('is_active', models.BooleanField(default=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('scheduled_class', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='academic.scheduledclass')),
                    ],
                    options={
                        'db_table': 'attendance_sessions',
                    },
                ),
                migrations.CreateModel(
                    name='Attendance',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('registered_at', models.DateTimeField(auto_now_add=True)),
                        ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                        ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                        ('accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                        ('ip_address', models.CharField(max_length=45)),
                        ('user_agent', models.TextField()),
                        ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='authentication.student')),
                        ('session', models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='attendance.attendancesession')),
                    ],
                    options={
                        'db_table': 'attendances',
                    },
                ),
                migrations.AddIndex(
                    model_name='attendancesession',
                    index=models.Index(condition=models.Q(('is_active', True)), fields=['token_hash'], name='idx_attendance_sessions_token'),
                ),
                migrations.AddIndex(
                    model_name='attendance',
                    index=models.Index(fields=['session'], name='idx_attendances_session'),
                ),
                migrations.AddIndex(
                    model_name='attendance',
                    index=models.Index(fields=['student'], name='idx_attendances_student'),
                ),
                migrations.AddConstraint(
                    model_name='attendance',
                    constraint=models.UniqueConstraint(fields=('session', 'student'), name='unique_attendance_per_session'),
                ),
            ],
            database_operations=[
                migrations.RunPython(create_attendance_tables, noop),
            ],
        ),
    ]
