# Generated by Django 5.2.11 on 2026-09-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_alter_scheduledclass_qr_duration_minutes'),
        ('attendance', '0002_attendancesession_attendance_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='attendancesession',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('scheduled_class',), name='unique_active_session_per_class'),
        ),
    ]
