# Generated by Django 5.2.11 on 2026-09-26 23:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0003_authorizedprofessoremail_professor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='AcademicGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_code', models.CharField(max_length=10)),
                ('term_period', models.CharField(max_length=20)),
                ('professor', models.ForeignKey(db_column='professor_id', on_delete=django.db.models.deletion.RESTRICT, related_name='groups', to='authentication.professor')),
                ('course', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.RESTRICT, related_name='groups', to='academic.course')),
            ],
            options={
                'db_table': 'academic_groups',
            },
        ),
        migrations.CreateModel(
            name='ScheduledClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('start_time', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('modality', models.CharField(choices=[('PRESENTIAL', 'Presencial'), ('VIRTUAL', 'Virtual')], default='PRESENTIAL', max_length=20)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Programada'), ('IN_PROGRESS', 'En curso'), ('COMPLETED', 'Finalizada'), ('CANCELLED', 'Cancelada')], default='SCHEDULED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(db_column='group_id', on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='academic.academicgroup')),
            ],
            options={
                'db_table': 'scheduled_classes',
                'ordering': ['start_time'],
            },
        ),
        migrations.AddConstraint(
            model_name='academicgroup',
            constraint=models.UniqueConstraint(fields=('course', 'group_code', 'term_period'), name='unique_group_per_term'),
        ),
    ]
