# Generated by Django 5.2.11 on 2026-09-27 19:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_scheduledclass_qr_duration_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledclass',
            name='qr_duration_minutes',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)]),
        ),
    ]
