# Generated by Django 5.2.17 on 2026-09-24 19:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

# DDL de SIA-QR.md. La tabla puede venir creada a mano, asi que es idempotente.
CREATE_PROFESSORS = """
CREATE TABLE IF NOT EXISTS professors (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    employee_code varchar(50) NOT NULL UNIQUE,
    first_name varchar(100) NOT NULL,
    last_name varchar(100) NOT NULL,
    department varchar(100)
)
"""


def create_professors_table(apps, schema_editor):
    schema_editor.connection.cursor().execute(CREATE_PROFESSORS)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_users_auth_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedProfessorEmail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'authorized_professor_emails',
            },
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Professor',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('employee_code', models.CharField(max_length=50, unique=True)),
                        ('first_name', models.CharField(max_length=100)),
                        ('last_name', models.CharField(max_length=100)),
                        ('department', models.CharField(blank=True, max_length=100, null=True)),
                        ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='professor_profile', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'db_table': 'professors',
                    },
                ),
            ],
            database_operations=[migrations.RunPython(create_professors_table, noop)],
        ),
    ]

